cozy/cozy-keys-browser

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/content/notification.css
- src/content/notificationBar.ts
- src/manifest.json
- src/notification/bar.html
- src/notification/bar.js
- src/notification/bar.scss
- src/popup/scss/variables.scss
- webpack.config.js
Change the design for the notification bar when a password can be added or updated.
See the final result:
> Restyle the notification bar

- src/services/browserPlatformUtils.service.spec.ts
Make the linter happy, which will be run in the future CI
> style: Fix lint

- karma.conf.js
- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/popup/accounts/login.component.spec.ts
- src/popup/accounts/login.component.ts
The user must enter his URL to login. This performs some checks on the input URL to prevent common mistakes.
Note the regexp is the one used in the cozy cloudery
> feat: Check the login url

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/popup/accounts/home.component.html
- src/popup/scss/buttons.scss
- src/popup/scss/variables.scss
* Add a register link
* Use Cozy guideline for buttons
Before/after:
> Better home page

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/background/runtime.background.ts
- src/popup/app.component.ts
- src/popup/scss/misc.scss
- src/popup/vault/groupings.component.html
* Do not open a new tab after installation of the extension
* Use a sad cozy icon if no cipher was found
* The message toast was overlapping with the tab menu: we move it up
* Use "Cozy password" instead of "Master password"
> UI improvements

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
- src/notification/bar.html
- src/notification/bar.js
We used to have a notification popup with a 'more options', mainly for demo purposes. We remove this in order to be in production soon.
> feat: Remove more options in notification

- src/content/notificationBar.ts
The save login notification was not working on Google.
This is because the submit button is outside the login `<form>`, while the extension made it mandatory to have the submit button inside the form in order to add en event listener on it.
We fix this by extending the search of the submit button in the whole html document and add an html selector specific to google: `div[role="button"]`.
> feat: Handle submit buttons outside of forms

- src/content/consts.ts
These names are used to find a submit button in a form: https://github.com/cozy/cozy-keys-browser/blob/master/src/content/notificationBar.ts#L461
> feat: Add more french login names

- src/popup/settings/options.component.html
- src/popup/settings/options.component.ts
We still displayed a TOTP entry in the options, while we do not support it yet
> fix: Remove TOTP option

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
> Change wordings

- src/_locales/en/messages.json
- src/_locales/fr/messages.json
On a wise suggestion of @Crash--
> feat: Notification wording

- src/services/auth.service.ts
After [this](https://github.com/cozy/cozy-keys-browser/commit/9f1a4e28d3395b556d60fdf621f32ec9e729dbb6), the unlocking was broken because the kdf params were missing [here](https://github.com/bitwarden/jslib/blob/b3d1e9d233aa7ed235d6ec0b26cdba41afa065ae/src/angular/components/lock.component.ts#L64-L65).
This is because this params were saved in the  `AuthService` parent class, in the `makePreloginKey` function. We fix that by using a child `makePreloginKey`.
> Fix unlock

- docs/overrides.md
We did some overrides and it is not possible for somebody new to know
everything about it. This documentation lists what we did.
It will also be useful to do the same tweaks in the mobile app.
> docs: Document all overrides

- CODEOWNERS
- src/popup/services/cozyClient.service.ts
- src/popup/settings/settings.component.html
- src/popup/settings/settings.component.ts
Redirect directly to passwords import page.
> Reactivate import entry in settings

- src/services/api.service.ts
Before : `Cozy Passwords ()`
After: `Cozy Passwords (Safari)`
> fix: Add Safari to the client name

- src/popup/settings/settings.component.html
- src/popup/settings/settings.component.ts
- src/safari/desktop.xcodeproj/project.pbxproj
We don't want to display the Premium Link on Safari since we'll have a reject from Apple...
> Disable premium

- src/popup/scss/box.scss
- src/popup/settings/options.component.html
- src/popup/settings/settings.component.html
* remove empty margin in top of the Options page
* remove useless separators in settings and options pages
* put in textColor the text of the first lavel of rows in options page
* correct left alignments in rows of the Options page
> Small ui improvements

- src/background/runtime.background.ts
- src/inPageMenu/loginMenu.js
- src/manifest.json
- src/services/abstractions/autofill.service.ts
- src/services/autofill.service.ts
Improve the rules to exclude input fields of the page where to add the in page menu (login or autofill).
> Login in page menu

- README.md
Add instructions to build the extension
> docs: Complete build instructions

- apps/browser/src/popup/services/cozyClient.service.ts
- apps/browser/src/vault/popup/components/cipher-row.component.html
- apps/browser/src/vault/popup/components/cipher-row.component.ts
- apps/browser/src/vault/popup/components/vault/vault-items.component.ts
- apps/browser/src/vault/popup/components/vault/view.component.html
- apps/browser/src/vault/popup/components/vault/view.component.ts
- libs/cozy/note.helper.ts
- libs/cozy/paper.helper.ts
- libs/cozy/queries.ts
- Display creation and update date for papers
- Sort papers by date
- Correctly fetch thumbnails (even if user is not logged in to the cozy instance on the browser)
> Multiples fixes for stream1

- libs/common/src/vault/models/domain/paper.spec.ts
- libs/common/src/vault/models/domain/paper.ts
- libs/common/src/vault/models/view/paper.view.ts
- libs/common/src/vault/services/cipher.service.ts
- libs/cozy/fields.helper.ts
- libs/cozy/note.helper.ts
- libs/cozy/paper.helper.ts
We we added paper data, we did not encrypt them for simplicity. Now that we have more experience, we encrypt them so that it is as close as bitwarden way of working.
> feat: Encrypt paper data

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/cozy/components/add-generic/add-generic.component.html
- apps/browser/src/cozy/components/add-generic/add-generic.component.ts
- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
- apps/browser/src/vault/popup/components/vault/vault-items.component.html
- apps/browser/src/vault/popup/components/vault/vault-items.component.ts
- apps/browser/src/vault/popup/components/vault/view.component.ts
- libs/common/src/models/api/contact.api.ts
- libs/common/src/vault/enums/cipher-type.ts
- libs/common/src/vault/models/data/cipher.data.ts
- libs/common/src/vault/models/data/contact.data.ts
- libs/common/src/vault/models/domain/cipher.ts
- libs/common/src/vault/models/domain/contact.ts
- libs/common/src/vault/models/response/cipher.response.ts
- libs/common/src/vault/models/view/cipher.view.ts
- libs/common/src/vault/models/view/contact.view.ts
- libs/common/src/vault/services/cipher.service.ts
- libs/common/src/vault/services/sync/sync.service.ts
- libs/cozy/contact.helper.ts
- libs/cozy/contactCipher.ts
- libs/cozy/queries.ts
- Contact cipher type and related classes
- Contact query
- Contact list
- Contact links (redirect to "Contacts" app on open contact, edit contact, ...)
> Contacts in extension foundation

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/popup/scss/misc.scss
- apps/browser/src/vault/popup/components/vault/view.component.html
- apps/browser/src/vault/popup/components/vault/view.component.ts
- libs/common/src/models/api/contact.api.ts
- libs/common/src/vault/models/data/contact.data.ts
- libs/common/src/vault/models/domain/contact.ts
- libs/common/src/vault/models/view/contact.view.ts
- libs/common/src/vault/services/cipher.service.ts
- libs/cozy/contact.helper.ts
> Add email and call action for contact ciphers

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/vault/popup/components/vault/view-custom-fields.component.html
- apps/browser/src/vault/popup/components/vault/view-custom-fields.component.ts
- apps/browser/src/vault/popup/components/vault/view.component.ts
- libs/common/src/models/api/field.api.ts
- libs/common/src/vault/models/data/field.data.ts
- libs/common/src/vault/models/data/label.data.ts
- libs/common/src/vault/models/domain/field.ts
- libs/common/src/vault/models/view/field.view.ts
- libs/common/src/vault/services/cipher.service.ts
- libs/common/src/vault/services/sync/sync.service.ts
- libs/cozy/contact.helper.ts
- libs/cozy/contact.lib.js
- libs/cozy/contactCipher.ts
- libs/cozy/fields.helper.ts
- Display contact fields (name, surname, company, address, ...) in view component
- Hide by default address subfields and allow to expand them
> Display contact fields (name, surname, company, address, ...) in view component

- apps/browser/src/autofill/services/autofill-constants.ts
- apps/browser/src/autofill/services/autofill.service.ts
- libs/common/src/models/api/field.api.ts
- libs/common/src/vault/models/data/field.data.ts
- libs/common/src/vault/models/domain/field.ts
- libs/common/src/vault/models/view/field.view.ts
- libs/common/src/vault/services/cipher.service.ts
- libs/cozy/contact.helper.ts
- libs/cozy/fields.helper.ts
We do what we need to use identity autofill for contact autofill to keep the same autofill quality.
> Leverage identity autofill for contact autofill 

- libs/common/src/vault/services/sync/sync.service.ts
Instead of doing 1 replace for bitwarden ciphers and 2 upsert for cozy ciphers, we update syncCiphers method to accept our cozy ciphers. So 1 replace will be enough for bitwarden and cozy ciphers and it is faster.
> Sync in the same time bitwarden and cozy ciphers

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/cozy/components/profiles-migration/profiles-migration.component.html
Also better pluralization if there is only 1 profile.
> Update profile migration content wording

- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
> Add encryption info title for secure notes and folders

- libs/cozy/contact.helper.ts
We want to display me as favorite so that it is available at first glance in the UI.
We leverage the fact that the favorite field is not defined by default.
> feat: Display me as favorite

- apps/browser/src/auth/popup/restoreHistory.component.ts
- apps/browser/src/popup/app-routing.module.ts
- apps/browser/src/popup/app.component.ts
- apps/browser/src/popup/services/history.service.ts
- libs/common/src/services/search.service.ts
Applying this commit after merge upstream 8b57bdb
> fix: Logins before every other types in search result

- apps/browser/src/background/runtime.background.ts
- apps/browser/src/popup/services/history.service.ts
Working Manifest V3 extension with service workers on Chrome.
> Fix manifest v3 build

- apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
- apps/browser/src/autofill/services/autofill-overlay-content.service.ts
**Before**
https://github.com/user-attachments/assets/eeb17c71-f4e0-4002-ad99-0ec37838e711
**After**
https://github.com/user-attachments/assets/0c1b5b05-a6d5-4a89-b24a-b31ed5557f22
> feat: Open inline menu on focus even if field is filled

- apps/browser/src/popup/scss/base.scss
- apps/browser/src/vault/popup/components/vault/add-edit.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
Remove space here
Add space here
> Various style issues

- libs/cozy/createOrUpdateCozyDoctype.ts
New template is :
qualification label (translated) - contact name
creation date
metadata label (translated): value
> feat: Update empty PDF paper content

- apps/browser/src/auth/popup/login.component.html
Other pages use button instead of a now.
> fix: Cancel button was invisible on login page

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/background/main.background.ts
We were logging out cozy client too late in the logout method :
- so it was not deleting the cozy client oauth clients
- and it was breaking the Bitwarden logout process leading to strange behavior
> fix: Cozy client logout

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/autofill/background/abstractions/notification.background.ts
- apps/browser/src/autofill/background/notification.background.spec.ts
- apps/browser/src/autofill/background/notification.background.ts
- apps/browser/src/autofill/background/overlay.background.spec.ts
- apps/browser/src/autofill/background/overlay.background.ts
- apps/browser/src/autofill/content/notification-bar.ts
- apps/browser/src/autofill/enums/notification-queue-message-type.enum.ts
- apps/browser/src/autofill/notification/abstractions/notification-bar.ts
- apps/browser/src/autofill/notification/bar.html
- apps/browser/src/autofill/notification/bar.ts
- apps/browser/src/background/main.background.ts
- libs/cozy/createOrUpdateCozyDoctype.ts
> Add a notification when a paper is created

- apps/browser/src/vault/popup/components/vault/vault-items.component.html
We will need to rethink how we add icons here totally for a cleaner solution.
> fix: Hardcoded fix for left arrow

- apps/browser/src/autofill/background/overlay.background.ts
- apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
- apps/browser/src/autofill/services/abstractions/autofill.service.ts
- apps/browser/src/autofill/types/index.ts
Redirect to the correct app to edit the desired value.
> feat: Add Edit option in ActionMenu

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/auth/popup/account-switching/account-switcher.component.html
- apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
- apps/browser/src/auth/popup/account-switching/current-account.component.html
- apps/browser/src/auth/popup/lock.component.html
- apps/browser/src/platform/popup/browser-popup-utils.ts
- apps/browser/src/popup/scss/base.scss
- apps/browser/src/popup/scss/box.scss
- apps/browser/src/popup/scss/misc.scss
- apps/browser/src/vault/popup/components/vault/current-tab.component.html
- apps/browser/src/vault/popup/components/vault/current-tab.component.ts
- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
- apps/browser/src/vault/popup/components/vault/vault-items.component.html
- apps/browser/src/vault/popup/components/vault/vault-items.component.ts
- apps/browser/src/vault/popup/components/vault/view.component.html
- package-lock.json
- package.json
> New account menu and unlock page

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/autofill/popup/settings/autofill-v1.component.html
- apps/browser/src/popup/app-routing.module.ts
- apps/browser/src/popup/scss/base.scss
- apps/browser/src/popup/scss/misc.scss
- apps/browser/src/vault/popup/components/vault/current-tab.component.html
- apps/browser/src/vault/popup/components/vault/current-tab.component.ts
- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
> Add suggestions in vault page

- apps/browser/src/autofill/background/overlay.background.ts
- apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
- apps/browser/src/autofill/services/abstractions/autofill.service.ts
- apps/browser/src/autofill/types/index.ts
When we want to modify the metadata of a file, we are redirected to the editing modal of the Mespapiers app.
> feat: Redirect paper edition

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/autofill/background/abstractions/notification.background.ts
- apps/browser/src/autofill/background/notification.background.ts
- apps/browser/src/autofill/background/overlay.background.ts
- apps/browser/src/autofill/enums/notification-queue-message-type.enum.ts
- apps/browser/src/autofill/notification/bar.html
- apps/browser/src/autofill/notification/bar.ts
Displayed after an autofill from the inline menu
> Add TOTP copied notification

- apps/browser/src/_locales/en/messages.json
- apps/browser/src/_locales/fr/messages.json
- apps/browser/src/auth/popup/home.component.ts
> feat: Display snackbar if Cozy does not exist

- apps/browser/src/vault/popup/components/action-buttons.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.html
- apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
- apps/browser/src/vault/popup/components/vault/vault-items.component.html
- apps/browser/src/vault/popup/components/vault/vault-items.component.ts
- libs/angular/src/vault/components/vault-items.component.ts
> Fix actions buttons for contacts and papers
