cozy/cozy-keys-browser

src/popup/app.component.ts
src/popup/app.module.ts
src/services/browserPlatformUtils.service.ts

Tracking was already disabled since this [commit](https://github.com/bitwarden/jslib/commit/f4c4f2802637f775c3bfba2ef4109350bc842b8f#diff-b351b37af83ee6f5ef2ac51a405511e9)
This PR removes useless instance of google analytics and calls to tracking.

Remove google analytics and tracking calls

---

webpack.config.js

The production bundler wasn't minimized, making `popup/vendor.js` too heavy to pass the firefox extension validation.

chore: Minimize bundler for production

---

.travis.yml

Add travis conf file for CI. The specificity here is the use of karma for the unit tests, which run an actual browser. It is thus necessary to enable a GUI as specified in the [doc](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui)

chore: Add travis conf

---

.travis.yml

The xvfb configuration was the one recommended for Ubuntu trusty, while we currently are on Ubuntu xenial : https://docs.travis-ci.com/user/gui-and-headless-browsers/

chore: Fix travis conf

---

src/content/notificationBar.ts

A DOM change could not be seen if it occured between the collect and the observe DOM timeout end. This was causing some save login notification not showing, especially with slow connection.
I reproduced (not systematically) the issue on trainline.fr with Firefox 71, after a first login/logout and another login in GPRS connectivity.
Note the original reason behind this timeout seems to be about the autofill: https://github.com/bitwarden/browser/commit/d19fcd6e4ccf062b595c2823267ffd32fd8e5a3d

feat: Remove observe DOM timeout

---

src/content/autofill.js
src/content/notificationBar.ts

Some sign-in forms don't use the HTML `<form>`. This prevented the add credentials
notification to show up, for example on itunesconnect.apple.com or mindfintech.fr.
We fix that by looking for sign-in forms by class name.
Note that for these situations, the use of the 'enter' button to sign-in seems broken: it will either won't submit, or, if it does, the notification won't show up.

feat: Handle sign-in forms with no HTML form

---

src/background/runtime.background.ts
src/browser/browserApi.ts
src/content/appInfo.ts
src/manifest.json
webpack.config.js

When the user arrives on the installation step in cozy-passwords, the app regularly sends `postMessage`, waiting for an answer from the extension. 
Once the extension is installed, it intercepts the message and answer back with its version.
See https://github.com/cozy/cozy-passwords/pull/2

feat: Communicate version to cozy-password message

---

src/_locales/en/messages.json
src/_locales/fr/messages.json
src/popup/settings/settings.component.ts

"Help" section uses the correct wording and redirects to https://support.cozy.io/category/378-gestionnaire-de-mots-de-passe

feat: Help redirects to the support page

---

overrides/jslib/src/services/sync.service.ts
src/background/main.background.ts
src/popup/services/cozyClient.service.ts
webpack.config.js

We want to update the synchronized_at on the io.cozy.oauth.clients every
time the extension is synced. It enables us to show this information in
cozy-settings.
To achieve that, I added a SyncService class that extends the jslib's
one and overrides its `setLastSync` method to call the
/settings/synchronized stack route. This class is imported when the
original one is imported. The webpack configs replaces the original one
with the override.

feat: Update synchronized_at on oauth client on each sync

---

src/content/autofill.js

A website might have badly-formed classes starting or finishing with spaces. In which case, the auto-fill would fail because of a bad selector, e.g. with trainline.fr

fix: Trim classes having whitespaces

---

src/background/main.background.ts
src/popup/services/sync.service.ts
webpack.config.js

When building for production, the alias used to override the
sync.service.ts file from the jslib was not resolved. A little research
showed that the problem is caused by the usage of the
AngularCompilerPlugin in the webpack config. But after reading the docs,
I was not able to fix the problem.
So the solution here is to not override the file, but to manually change
the import path in files were it's imported.

fix: Don't override whole jslib file

---

src/background/main.background.ts

The logout notification was not working properly, failing with a `Token not found`.
This was because all the services cleanup were run in parallel, while some might need the token, which is being cleared during the process.
Therefore, we run the `clearToken` after all the services have finished to clear themselves.

fix: clear token after others services in logout

---

src/popup/accounts/home.component.html
src/popup/scss/pages.scss

On the home page, the signup link styles make it overflow on the login button. So clicking on the login button actually opened a new browser tab on the cozy.io website.
The `center-content` class' role is to... center content. Using it on this element is pretty weird. I just replaced it with a custom class that properly align the element without making it overflow its sibling.

fix(home): Avoid signup link overflow on login button

---

src/background/main.background.ts
src/services/export.service.ts

The original Bitwarden extension doesn't include organizations ciphers
in the exported data. In our case, we want to include it.
I extended the original ExportService and had to copy/paste the getExport method to override it. And also the buildCommonCipher method because it's declared as private in the jslib, so it's impossible to call it from our class.

feat: Export all ciphers

---

package.json
src/background/main.background.ts
src/services/api.service.ts

The stack now accepts a `clientName` property on the login request on
bitwarden (see https://github.com/cozy/cozy-stack/pull/2346). We use it
to pass a custom client name like "Cozy Password (Firefox)". This way,
on cozy-settings we have a better understanding on which client comes
from where.

Pass a custom client name on login

---

src/content/notification.css
src/notification/bar.scss

A font rendering difference between chrome and firefox makes the buttons wider on firefox than on chrome in the notification bar:
|chrome|firefox|
|------|-------|
|![image](https://user-images.githubusercontent.com/1606068/73532552-34df2100-441d-11ea-8f33-98318bba8c4a.png)|![image](https://user-images.githubusercontent.com/1606068/73532531-285ac880-441d-11ea-9bef-cb7963929dd8.png)|
To fix this, I did two things:
* A wider notification bar, so in firefox the buttons render nicely
* Use display flex, so the buttons shrink by default but don't wrap if  there's not enough space
Now the rendering on firefox is ok:

fix(notification): Prevent buttons wrap

---

src/background/main.background.ts
src/models/response/identityTokenResponse.ts
src/popup/services/cozyClient.service.ts
src/popup/services/services.module.ts
src/services/api.service.ts
src/services/auth.service.ts

To achieve this, I had to instantiate the AuthService in the main background and share it in the ServicesModules. Otherwise it was impossible to access the AuthService from the main background.
I also had to extend the original `IdentityTokenResponse` to add the `clientId` and `registrationToken` that are now returned by the stack on login (see https://github.com/cozy/cozy-stack/pull/2347). These infos are required to be able to call the [`DELETE /auth/register/:client-id` route](https://docs.cozy.io/en/cozy-stack/auth/#delete-authregisterclient-id).

feat: Remove oauth client on logout

---

src/_locales/en/messages.json
src/_locales/fr/messages.json
src/popup/vault/add-edit.component.ts

When a user deletes a cipher, he is prompted to confirm. When the cipher
is linked to the cozy organization, we show a message telling him that the
konnectors accounts that use the cipher being deleted will be removed,
thus stopping automatic import of his data.

feat: Tell that konnectors accounts will be deleted on cipher delete

---

src/popup/services/konnectors.service.ts

Even though it is unlikely to have more than 100 suggestion apps/konnectors, it is better to query them all.

fix: Query all konnectors and apps suggestion

---

src/_locales/fr/messages.json
src/popup/services/konnectors.service.ts

The TODO made no sense as there is no account when suggesting a konnector based on the cipher

Small fixes

---

src/popup/services/services.module.ts
src/services/auth.service.ts

After https://github.com/cozy/cozy-keys-browser/pull/64, the icon color was not changing when the user loggedin (it should go from grey indicating that the extension is not loggedin, to blue indicating that the extension is loggedin).
The problem is caused by the `loggedIn` message not being received by the `RuntimeBackground`. This message is sent by the `AuthService` through the `MessagingService`. At first I tried to get the `MessagingService` created in `MainBackground` (and that is used by the `AuthService`, as this one is also created by the `MainBackground`) instead of creating a new one. But it didn't work and I couldn't find why: the same `MessagingService` instance is used everywhere, but it doesn't catch the `loggedIn` messages.
So the solution I found is to keep the creation …

fix: Change icon color on login

---

src/background/main.background.ts
src/popup/services/konnectors.service.ts
src/popup/vault/add-edit.component.ts

The apps suggestion was broken since this [commit](https://github.com/cozy/cozy-keys-browser/commit/d1e4d632ed802cd347b11cfb1a74c8826d20faaa), as `queryAll` does not return the `data` object, unlike `query`

Fix apps suggestion

---

docs/extension-status.md
src/background/main.background.ts
src/background/runtime.background.ts
src/browser/browserApi.ts
src/content/appInfo.ts

The goal is to be able to tell whether the extension is connected or not. To achieve this, we need the `appInfo` content script to check if the user is currently authenticated or not. But it doesn't have access to the services. So we use `appInfo` as a bridge, as described in https://krasimirtsonev.com/blog/article/Send-message-from-web-page-to-chrome-extensions-background-script.
The app triggers a `checkextensionstatus` on `document`, which is caught by `appInfo`. Then `appInfo` sends a message to the extension. The `MainBackground` catches this message and responds to it. `appInfo` then triggers a `extensioninstalled` or `extensionconnected` event according to the status returned by `MainBackground`. The app can then catch these events and use it to behave like it wants (in our case, …

feat: Send extension status through appInfo content script

---

src/safari/desktop/AppDelegate.swift

Since it's an Apple's requirement to pass the review : 
"The user interface of your app is not consistent with the macOS Human Interface Guidelines.
Specifically, we found that when the user closes the main application window there is no menu item to re-open it.
Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed."
As our desktop app is a single window app, let's close the app when we close the window. It's just a boolean :)

fix: Close App when we close the window

---

src/popup/vault/groupings.component.html
src/popup/vault/groupings.component.ts

Sections without ciphers in the Vault page were shown even if
no ciphers from the corresponding type were present.

fix: Do not show empty sections

---

src/safari/safari/safari.entitlements

You got a rejection from apple saying that we don't have a functionnality that use this permission. 
Tried without, and it seems to works well :
- added an account Cozy Pass Mobile and it appears on my extension panel 
- logged to a website and had the popup to save my credentials

fix: Remove not needed entitlements

---

src/popup/vault/groupings.component.html
src/popup/vault/groupings.component.ts

This PR fixes 2 things:
- Avoid errors when listing ciphers by initializing the expected  structures
- Display the trash even when no ciphers are available.
:warning: This should be merged after https://github.com/cozy/cozy-keys-browser/pull/90

Fixes on grouping view

---

src/popup/vault/add-edit.component.ts
src/popup/vault/utils.ts
src/popup/vault/view.component.ts

Since these bitwarden's
[changes](https://github.com/cozy/cozy-keys-browser/commit/411630296536340c4db998b1dd96faacc619e59e#diff-21589230df2863fc1476560862b8f002), it is now possible to delete a cipher from the View component. However, we need
to override it from the jslib to display a specific message for ciphers shared with Cozy.
This also allows to call the same method from the 2 components using
the delete, ViewComponent and AddEditComponent.

refactor: Override jslib delete

---

package.json

`npm install` was failing on the submodules init if the source code was downloaded from a .zip archive instead of a `git clone`.

fix: Init git before running submodules

---

src/background/main.background.ts
src/background/runtime.background.ts
src/popup/services/cozyClient.service.ts
src/popup/services/konnectors.service.ts
src/popup/services/sync.service.ts

*    Fix potential infinite loops that might be caused when a communication with the stack failed during the logout (as the failure will it self call the logout callback)
*    Improve cozy-client handling: we force an automatic instance recreation when the cozy-client's token is no longer the same than the one saved by the jslib. This was causing errors when the token was refreshed by the jslib and cozy-client was using the old credentials.

Fix infinite loop

---

src/_locales/en/messages.json
src/_locales/fr/messages.json

Some users have to use their organization password and not their "cozy" password (OIDC login) . The previous wording would introduce ambiguity (cozy password vs organization password).

fix: change password hints to prevent ambiguity on which password to use

---

src/popup/accounts/login.component.spec.ts
src/popup/services/cozySanitizeUrl.service.ts

Having a trailing slash in the cozy address would produce a bad vault
url containing two successive slashes (`//`)
This fix remove the trailing slash from the cozy address so only one is
present in the final vault url

fix: handle trailing slash in cozy address

---

src/manifest.json

1.54.3 already exists I don't know why it has not been versioned. So new version should be 1.54.4

feat: bump version to 1.54.4

---

src/popup/components/ciphers-list.component.spec.ts
src/popup/components/ciphers-list.component.ts
src/tools/strings.spec.ts
src/tools/strings.ts

Credit Cards subTitles should be displayed correctly even if some parts
of the date are missing or have a wrong format
This PR fixes the following cases:
- Year is missing -> Now displays `01/__`
- Month is missing -> Now displays `__/21`
- Year has wrong format (ex: `ABCD`) -> Now displays `01/__`
- Year has only 2 digits (ex: `21`) -> Now displays `01/21`
- Both year and month are missing -> Now displays only the card type and number
- Card type and card number are missing -> leading comma is not displayed anymore
- Every subTitle parts are missing -> Now displays nothing
Before (display is broken due to exception thrown in code when Year is missing)
After

fix: display correct Card subTitle even if some date parts are missing

---

src/background/runtime.background.ts
src/popup/services/cozyClient.service.ts

CozyClient is now correctly logged-out  when vault is logged-out
This fix a bug where flags were not cleared after a logout

fix: logout CozyClient on vault logout

---

src/background/main.background.ts
src/background/runtime.background.ts

Fix unlock with passphrase:
Edit unlock code to comply with bitwarden/jslib#404 and
bitwarden/jslib#407
Fix unlock with pin code:
`chrome.runtime.sendMessage` cannot be  used from background process so
we should use `this.processMessage` instead

fix: unlock on pageMenu

---

src/popup/settings/settings.component.ts

Settings' `Import` button now correctly redirects the user by handling
subdomain type (`nested` or `flat`)

fix: correctly handle subdomain type on settings/import

---

src/background/runtime.background.ts

After a logout, if the user login with a new instance url, then this
new instance url should be used by `NotificationService`

fix: init NotificationService with correct url on login

---

src/_locales/en/messages.json
src/_locales/fr/messages.json

We chose to use `address` instead of `URL` as it is more user friendly
See this discussion for more information : https://github.com/cozy/cozy-pass-mobile/pull/52#discussion_r759374161

fix: homogenize usage of `address` instead of `URL`

---

src/manifest.json

"Cozy Keys" was displayed in the side bar, which is not the product name

fix: Use Cozy as sidebar title

---

.travis.yml
src/popup/settings/options.component.html

In 8a8cc6442254e64919104d085ddae78d19d41362, we removed by error the option's entries that enable/disable InPage menu and connectors suggestion after creating an eligible cipher
This PR restores those features
Related PRs: #24 and #90 
Related Commit: 8a8cc6442254e64919104d085ddae78d19d41362

fix: Restore options to enable/disable inPageMenu and connectors suggestions

---

src/inPageMenu/loginMenu.html
src/popup/settings/folder-add-edit.component.html
src/popup/vault/add-edit.component.html
src/popup/vault/ciphers.component.html
src/popup/vault/groupings.component.html

Everything protected in the vault should be considered as sensible data that should not leak through browser's enhanced spellcheck
So we want to disable spellcheck on cozy-pass fields like password fields, names, urls, notes, address etc
This commit does not handle `send` feature fields as it deactivated and so we are not able to test it. But this should be considered if we implement it in the future
More info: https://www.otto-js.com/news/article/chrome-and-edge-enhanced-spellcheck-features-expose-pii-even-your-passwords
Related issue: bitwarden/desktop#842
___
This PR reflects https://github.com/cozy/cozy-pass-web/pull/84

feat: Prevent spellcheck feature on form fields

---

src/popup/accounts/login.component.spec.ts
src/popup/accounts/login.component.ts

When the user click on "I forgot my password" link, if this cozy is in
an OIDC context and if the CozyPass onboarding is not done yet, then we
want to redirect to the onboarding instead of the
`/auth/passphrase_reset` route
This behavior is because OIDC users have 2 different passwords, the one
from the OIDC portal, and the one for CozyPass
When the user logs into CozyPass Browser for the first time, they may
not know that they should use a different password from the OIDC portal
so we should not redirect into the portal, but to the CozyPass
onboarding
___
TODO:

feat: Redirect to CozyPass web onboarding on "forgot password" for OIDC

---

src/popup/settings/export.component.html

In the current implementation we use a Cozy override of `ExportService`
During previous merge upstream, we did not apply latest code change from the base class, so the override method still implements the old behaviour
However we received the UI update that was referencing `.json (Encrypted)` option that is not implemented in our version yet
So we deactivate this option until we fix the implementation (this should be done after the in-progress merge upstream)

fix: Disable `.json (Encrypted)` option in the export screen

---

src/_locales/en/messages.json
src/_locales/fr/messages.json

I don't know how [webVaultHostname](https://github.com/bitwarden/jslib/blob/b3d1e9d233aa7ed235d6ec0b26cdba41afa065ae/src/angular/components/lock.component.ts#L49) can be empty in some case, but here is an exemple of what I get sometimes

fix: Default placeholder hostname

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/popup/scss/misc.scss
apps/browser/src/popup/scss/pages.scss
apps/browser/src/vault/popup/components/vault/add-edit.component.html
apps/browser/src/vault/popup/components/vault/view-custom-fields.component.html
apps/browser/src/vault/popup/components/vault/view-custom-fields.component.ts
apps/browser/src/vault/popup/components/vault/view.component.html
apps/browser/src/vault/popup/components/vault/view.component.ts
libs/common/src/models/api/paper.api.ts
libs/common/src/vault/models/data/paper.data.ts
libs/common/src/vault/models/domain/paper.ts
libs/common/src/vault/models/view/paper.view.ts
libs/cozy/fields.helper.ts
libs/cozy/note.helper.ts
libs/cozy/paper.helper.ts
libs/cozy/paperCipher.ts
package-lock.json
package.json

Display notes and papers, in other words for notes and papers in the cipher `View`:
- add paper thumbnail (exemple in the screenshot is a screenshot itself)
- display paper metadata as `Fields`
- modify "Edit" and "Open in Cozy" links to redirect to mespapiers or notes app
- hide share action
- hide clone action
- add print action
- add download action
- UI and wording updates

Display notes and papers

---

libs/cozy/paperCipher.ts

If something failed during paper import, it was failing the full sync process making the extension unusable. Now we return an empty array if there is an error during paper import so the rest of the extension will work fine. There will be only no papers.

Do not fail sync when error during paper import

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/popup/app.module.ts
apps/browser/src/vault/popup/components/vault/view-custom-fields.component.html
apps/browser/src/vault/popup/components/vault/view-expiration-date.component.html
apps/browser/src/vault/popup/components/vault/view-expiration-date.component.ts
apps/browser/src/vault/popup/components/vault/view.component.html
apps/browser/src/vault/popup/components/vault/view.component.ts
libs/angular/src/vault/components/view-custom-fields.component.ts
libs/common/src/enums/fieldSubType.ts
libs/common/src/models/api/field.api.ts
libs/common/src/vault/models/data/expiration-date.data.ts
libs/common/src/vault/models/data/field.data.ts
libs/common/src/vault/models/domain/field.ts
libs/common/src/vault/models/view/field.view.ts
libs/common/src/vault/services/cipher.service.ts
libs/cozy/fields.helper.ts
libs/cozy/note.helper.ts
libs/cozy/paper.helper.ts
libs/cozy/paperCipher.ts
libs/cozy/queries.ts

**Favorite**
Allow to favorite/unfavorite a paper directly from the view mode (not from the edit mode). Very different than for bitwarden ciphers. It saves the favorite value in the in.cozy.files `cozyMetadata`.
Related : https://github.com/cozy/cozy-stack/pull/4355 https://github.com/cozy/cozy-pass-web/pull/122
**Expiration annotation**
Display an expiration annotation for expiration date in paper fields (can be 'Expired' or 'Expire in x days').
**Misc**
1 bug fix and 1 refactoring

Favorite and expiration annotation

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/auth/popup/login.component.ts
apps/browser/src/background/main.background.ts
apps/browser/src/popup/scss/base.scss
apps/browser/src/popup/scss/box.scss
apps/browser/src/popup/scss/buttons.scss
apps/browser/src/popup/scss/misc.scss
apps/browser/src/popup/scss/variables.scss
apps/browser/src/popup/services/cozyClient.service.ts
apps/browser/src/popup/settings/options.component.ts
libs/angular/src/services/theming/theming.service.ts
libs/common/src/abstractions/state.service.ts
libs/common/src/enums/themeType.ts
libs/common/src/models/domain/global-state.ts
libs/common/src/services/state.service.ts

When the user log in a Cozy instance, we want to apply the correct
theme based on the instance configuration but also on the user's
preferences
The instance configuration is defined by the
`passwords.theme.default-contrasted`. If this flag is true, then the
default theme should be the `LightContrasted` one. Otherwise the
`System` theme should be applied
The user's preferences are defined when the user changes the app theme
from the settings page. From that point we want to keep the selected
theme even when the user logs out
If the user did not change the app theme from the settings page, then a
log out should revert to the `LightContrasted` theme, which is the
app's default theme
Note that if the instance's flag is true, then we want to enforce the
`LightContrasted` whatever if the user …

feat: Add new theme `LightContrasted` and apply it when necessary

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/cozy/components/profiles-migration/profiles-migration.component.html
apps/browser/src/cozy/components/profiles-migration/profiles-migration.component.ts
apps/browser/src/popup/app.module.ts
apps/browser/src/popup/scss/cozy-profiles-migration.scss
apps/browser/src/popup/scss/misc.scss
apps/browser/src/popup/scss/popup.scss
apps/browser/src/vault/popup/components/vault/add-edit.component.ts
apps/browser/src/vault/popup/components/vault/cozy-utils.ts
apps/browser/src/vault/popup/components/vault/current-tab.component.html
apps/browser/src/vault/popup/components/vault/vault-filter.component.html
apps/browser/src/vault/popup/components/vault/vault-items.component.html
apps/browser/src/vault/popup/components/vault/view.component.html
apps/browser/src/vault/popup/components/vault/view.component.ts
libs/common/src/abstractions/state.service.ts
libs/common/src/models/domain/global-state.ts
libs/common/src/services/state.service.ts
libs/cozy/contactCipher.ts
libs/cozy/paperCipher.ts

We will soon remove the concept of `Profiles` and replace it by Cozy's `Contacts`
Because the user's vault is encrypted, we cannot do an automatic migration on server side
Also we prefer no to do a migration on the client's side due to the sensible nature of the data
Instead we want to warn the user that the `Profile` concept will be removed soon and that they need to migrate their data by themselves
We give the user some delays, after which the remaining `Profiles` will be moved to the trash and so become readonly and will be ignored by autofill capabilities
Related PR: cozy/cozy-pass-web#124
Related PR: cozy/cozy-pass-mobile#96
____

[VER-355] feat: Add Profile migration Alert and move all Profiles to trash after some delay

---

apps/browser/src/background/main.background.ts
apps/browser/src/cozy/realtime/RealtimeNotifications.ts
apps/browser/src/popup/services/cozyClient.service.ts
libs/cozy/contact.helper.ts
libs/cozy/paper.helper.ts
libs/cozy/paperCipher.ts
libs/cozy/queries.ts
package-lock.json
package.json

We want the extension to keep synchronized with the Cozy when a contact or a paper is created, edited or deleted from the cozy-contact webapp
The NotificationsService is responsible to keep the vault synchronized item is created outside of the extension
This service only works for Bitwarden items like ciphers or organization, but newly added Contacts and Papers are Cozy's concepts and so are not propagated through the Bitwarden's realtime mechanism
To allow this we must rely on the CozyClient's realtime capabilities
The first idea was to integrate those into the NotificationsService class, but we found that it can be fully isolated into a Cozy specific class. So we created the RealtimeNotifications class that is called from inside CozyClientService

feat: Add realtime for contacts and papers

---

apps/browser/src/cozy/realtime/RealtimeNotifications.ts
libs/common/src/vault/models/domain/cipher.ts
libs/common/src/vault/models/domain/contact.ts
libs/common/src/vault/models/domain/field.ts
libs/common/src/vault/models/domain/paper.ts
libs/common/src/vault/services/cipher.service.ts
libs/common/src/vault/services/sync/sync.service.ts
libs/cozy/contact.helper.ts
libs/cozy/contactCipher.ts
libs/cozy/fields.helper.ts
libs/cozy/note.helper.ts
libs/cozy/paper.helper.ts
libs/cozy/paperCipher.ts
libs/cozy/queries.ts

We were converting papers/contacts to CipherResponse because it is the model used by default during the sync.
Here we choose to convert to CipherData instead because :
- it help us add a fallback to the sync. When papers/contacts sync fail, we use the previous papers/contacts stored locally (they are stored as CipherData)
- the conversion is simplier (it involves less classes)
- we can still inject our papers/contacts during the sync thanks to the upsert method

Convert papers/contacts to CipherData instead of CipherResponse

---

apps/browser/src/background/main.background.ts
apps/browser/src/background/runtime.background.ts

When doing a logout we wan't the extension to also logout the Cozy's Oauth client
This was done from the `runtime.background.ts` file so the action is done when the user clicks on the Settings logout button
But this is not the only scenario that can produce a logout
This is the case when the user changes their password from cozy-settings. In that scenario, the cozy-stack will send a `logout` notification to the Bitwarden's realtime stream, and so the extension will react by doing a logout
To have the OAuth logout on both scenario we want to move the related code into `main.background.ts`

[VER-446] fix: Correctly logout OAuth client on logout notification

---

apps/browser/src/popup/scss/misc.scss
apps/browser/src/vault/popup/components/cipher-row.component.ts

When a thumbnail URL is invalid, it triggers the onThumbnailError handler and we display a default thumbnail in CSS. If the HTML view is reloaded (which happens a lot), it triggers again and again the onThumbnailError and the default thumbnail in CSS handler leading to a blinking thumbnail.
Now we change directly the thumbnail URL with the default one. So no onThumbnailError handler triggered. When the sync will be done, a new cipher row will a new thumbnail URL.

Fix blinking thumbnail row

---

apps/browser/src/models/account.ts
apps/browser/src/services/browser-state.service.ts
apps/browser/src/vault/popup/components/cipher-row.component.ts

KonnectorsOrganization is currently saved in the account InMemory storage as an object
We found that this may produce DeadObjects errors on Firefox due to the way it manage memory
Exemple scenario for reproducing this problem: open the Cozy Connectors folder, close the extension popup and re-open it. The ciphers will lose their "shared with Cozy" icons and the `can’t access dead object` error should appear in the devtools
We found that storing the info in the account as a string instead of an object would prevent the issue to happen
We could have also use `defaultOnDiskOptions` instead of `defaultInMemoryOptions` to save the `KonnectorsOrganization` data, but the string option seems to have less possible side effects
Related link: …

[VER-507] fix: Correctly display Konnectors icons after closing/reopenning the extension's popup

---

apps/browser/src/vault/popup/components/cipher-row.component.html

In previous commit we moved the `shared` icon on the cipher row's details line
This line is displayed only when the cipher has a subtitle, so if a cipher is shared but has no subtitle, then the `shared` icon will not be displayed
This commit fix this by displaying the detail line if the cipher has a subtitle OR if it is shared
This may produce a weird display but the case is rare enough to be problematic

[VER-507] fix: Display shared icon on cipher row even when no subtitle

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/cozy/components/encrypted-info/encrypted-info.component.html
apps/browser/src/cozy/components/profiles-migration/profiles-migration.component.html
apps/browser/src/cozy/components/profiles-migration/profiles-migration.component.ts
libs/common/src/abstractions/state.service.ts
libs/common/src/models/domain/account.ts
libs/common/src/models/domain/global-state.ts
libs/common/src/services/state.service.ts

"I understand" button hide the profiles migration component until the next logout/login.
Also moved `profilesCleanDeadline` to `account.settings` so it will avoid two users to share the same `profilesCleanDeadline`.

Add an "I understand" button to profiles migration component

---

apps/browser/src/cozy/components/add-generic/add-generic.component.html

Folders only contains end to end encrypted elements. So no contacts.

Do not allow to add contacts in folders

---

apps/browser/src/autofill/content/menuCtrler.js
apps/browser/src/autofill/services/autofill.service.ts
apps/browser/src/background/runtime.background.ts
apps/browser/src/cozy/autofill/evaluateDecisionArray.spec.ts
apps/browser/src/cozy/autofill/evaluateDecisionArray.ts
apps/browser/src/inPageMenu/menu.html
apps/browser/src/inPageMenu/menu.js
apps/browser/src/vault/popup/components/vault/current-tab.component.ts
libs/common/src/vault/services/cipher.service.ts

We want Contacts ciphers to appear in the InPage menu
In order to keep the menu usable, for now we limite the menu to display only `me` and favorites contacts
In the future we may implement a search feature allowing to access other contacts

feat: Handle contacts in inPageMenu

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/vault/popup/components/vault/current-tab.component.html
apps/browser/src/vault/popup/components/vault/current-tab.component.ts
libs/common/src/vault/services/cipher.service.ts
libs/cozy/contact.helper.ts

fix: Invert order of contacts and profiles in current tab
fix: Migrate profile setting wording
fix: Show nothing in "For this web page" if a type is disabled for this page
fix: Sort paper by date was not working because missing creation date

Order and wording fixes

---

apps/browser/src/inPageMenu/menu.js

After a page load, we needed to click multiple times on the in page menu to display it. It was because we used "#contact-row-list" everywhere, except in one place where we used "#contacts-row-list" leading to errors.

fix: Do not need to click multiple times in page menu to display it

---

apps/browser/src/inPageMenu/menu.js

Following previous fix that avoid _testHash to crash (99ae740), contacts were
not displayed because we consider them as identities, so we never removed the "hidden" class.
Let's remove it if identities "hidden" class is removed.

fix: Display again contacts in in page menu

---

libs/common/src/services/search.service.ts

For example, it avoids to have 100 Free invoices before 1 Free login.

feat: Logins before every other types in search result

---

apps/browser/src/manifest.json

Mozilla Addons requires Firefox min version >= 58.0. We set the version of the Bitwarden merge upstream which is 91.0

fix: Update Firefox min version to publish

---

apps/browser/docs/T08.0-Identity-with-paper-data.html
apps/browser/docs/index.html
apps/browser/src/autofill/enums/autofill-field.enums.ts
apps/browser/src/autofill/services/abstractions/inline-menu-field-qualifications.service.ts
apps/browser/src/autofill/services/autofill-constants.ts
apps/browser/src/autofill/services/autofill-overlay-content.service.ts
apps/browser/src/autofill/services/autofill.service.spec.ts
apps/browser/src/autofill/services/autofill.service.ts
apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
apps/browser/src/background/main.background.ts
apps/browser/src/popup/services/services.module.ts
libs/cozy/mapping.ts

In this PR, I add the foundation of autofilling paper data when autofilling a contact by taking as example the id card number.
https://github.com/user-attachments/assets/38f8935b-e5d5-4902-a816-5a1a2c7e2220
The paper data autofill expand the fillscript of a contact. 
Tested : 
- contact autofill from popup fill the id card number
- id card number field open the inline menu with contacts
- contact autofill from inline menu fill the id card number

Foundation of paper autofilling paper data with id card number

---

apps/browser/src/autofill/background/abstractions/overlay.background.ts
apps/browser/src/autofill/background/overlay.background.ts
apps/browser/src/autofill/overlay/inline-menu/abstractions/autofill-inline-menu-list.ts
apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
apps/browser/src/autofill/services/abstractions/autofill.service.ts
apps/browser/src/autofill/services/autofill-overlay-content.service.ts
apps/browser/src/autofill/services/autofill.service.ts

First two commits have been cherry-picked from `feat/inline-menu-basics`.

Autofill only one field

---

apps/browser/src/popup/services/cozyClient.service.ts
libs/common/src/platform/abstractions/environment.service.ts
libs/common/src/platform/services/default-environment.service.ts

Since the merge upstream, the method of retrieving the cozy URL has changed. (see 4a2dee6)
The new approach was not functional.
As the `this.webVaultUrlSync` property defines its value in an async method, when `getCozyURL()` is called `this.webVaultUrlSync` is not yet set.

fix: Redirect button to the Cozy

---

apps/browser/src/vault/popup/components/vault/cozy-utils.ts
libs/cozy/contactCipher.ts
libs/cozy/paperCipher.ts

Some toasts display the same information twice.
This change ensures that only the title is displayed in these toasts, giving the user a cleaner, more concise experience.

fix: Duplicate toast informations

---

apps/browser/src/popup/scss/base.scss

fix: Hide cross close button in search bar

---

apps/browser/docs/T08.0-Identity-with-paper-data.html
apps/browser/src/autofill/enums/autofill-field.enums.ts
apps/browser/src/autofill/services/abstractions/inline-menu-field-qualifications.service.ts
apps/browser/src/autofill/services/autofill-constants.ts
apps/browser/src/autofill/services/autofill-overlay-content.service.ts
apps/browser/src/autofill/services/autofill.service.ts
apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
libs/cozy/mapping.ts

It is still very verbose, but for the moment I think that it is not the moment to factorize the code : 
- we still do not know if there will be edge cases
- it is also verbose on Bitwarden side, so I do not want to factorize only part of the code, or I do not want to factorize their code, to avoid merge upstream conflict
Numéro de passport
Numéro de titre de séjour
Numéro de carte grise
Code ANTS
Plaque d'immatriculation
IBAN
BIC
Numéro fiscal
Revenu fiscal de référence

feat: Add more paper data in autofill

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html
apps/browser/src/tools/popup/settings/about-page/about-page.component.html

It disappeared, most likely in a merge upstream.

feat: Bring back about link and popup

---

apps/browser/src/autofill/background/abstractions/overlay.background.ts
apps/browser/src/autofill/background/overlay.background.ts
apps/browser/src/autofill/overlay/inline-menu/abstractions/autofill-inline-menu-list.ts
apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
libs/cozy/createOrUpdateCozyDoctype.ts
libs/cozy/getCozyValue.ts

Ajout de la sauvegarde de l'édition d'un champs ambigu (tel, etc) ou du nom d'un contact.
A l'exception de l'adresse qui est pour le moment pas encore assez bien détectée pour être fiable.

feat: Save attribute value in contact

---

apps/browser/src/cozy/realtime/RealtimeNotifications.ts
package-lock.json
package.json

When we had a realtime 'created' contact event, we added a cipher to the cipher list but the CozyClient store was not filled. So in the inline menu, we would see the contact but not autofill it because to autofill, we do a `client.query(query, { executeFromStore })` on the contact which returned null.

fix: Update CozyClient store on realtime events

---

apps/browser/src/background/runtime.background.ts
apps/browser/src/vault/popup/components/vault/current-tab.component.ts
apps/browser/src/vault/popup/components/vault/vault-items.component.ts
apps/browser/src/vault/popup/components/vault/view.component.ts

We customized Bitwarden autofill which now need a Cozy Client store with all the contacts inside.
Now with Manifest V3, there are :
- an autofill service and a CozyClient service for the background
- an autofill service and a CozyClient service for the extension popup
But only the CozyClient service of the background has its store filled with all the contacts inside fetched during the fullSync.
So we send the autofill action from the extension popup to the background.

feat: Do autofill when clicking on autofill buttons on popup

---

apps/browser/src/autofill/background/abstractions/overlay.background.ts
apps/browser/src/autofill/background/overlay.background.ts
apps/browser/src/autofill/overlay/inline-menu/abstractions/autofill-inline-menu-list.ts
apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
libs/cozy/contact.helper.ts
libs/cozy/createOrUpdateCozyDoctype.spec.ts
libs/cozy/createOrUpdateCozyDoctype.ts
libs/cozy/getCozyValue.spec.ts
libs/cozy/getCozyValue.ts
libs/cozy/mapping.ts

Last implementation added support of addresses, but we lost the ability to know if we save a value to a contact or to a paper.
I changed the logic a little bit to support it again.
Kept :
- InputRef and InputRefValue duality (one for HTML element and one with the HTML element value)
- address is managed in a special case
- type and label are sent one time
Changed :
- we send the fieldQualifier with the HTML element value to be able to find the model.
So instead of sending :
{
"street": "rue des champs" }
we send  :
{
"key": "street", "fieldQualifier": "identityAddress1", // allow to get the model "value": "rue des champs" }
Also added country in hidden fields.

fix: Add a paper works again

---

apps/browser/src/autofill/background/overlay.background.ts
apps/browser/src/autofill/services/abstractions/autofill.service.ts
apps/browser/src/autofill/services/autofill.service.ts
libs/cozy/createOrUpdateCozyDoctype.ts

If we have two fields of the same type, for example tel1 and tel2.
If we focus on tel2, we ignore tel1 and autofill tel2 and the rest of the form.

feat: Autofill the focus field first

---

apps/browser/src/vault/popup/components/vault/current-tab.component.ts
apps/browser/src/vault/popup/components/vault/vault-items.component.ts
apps/browser/src/vault/popup/components/vault/view.component.ts

In 6d3f39d1a29a4343977b5c242387a87ebfb6c654, we introduce a special way to do the autofill for Chrome because of Manifest 3. But this way does not work for Firefox which still use the Manifest 2 for the moment so let's add a strict check.

fix: Do autofill when clicking on autofill buttons on popup on Firefox

---

apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts

When the field was cleared, the focus was lost.
We want to keep it from the moment you click once on it.

feat: Keep focus on search bar

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json
apps/browser/src/auth/popup/login.component.html

Firefox Store is blocking the release because we have "login" and "logIn" key

fix: Remove duplicate login key

---

apps/browser/src/popup/services/cozyClient.service.ts
libs/common/src/platform/sync/default-sync.service.ts
libs/cozy/contactCipher.ts
libs/cozy/paperCipher.ts
libs/cozy/queries.ts
libs/cozy/sync.ts

Before we did the "fetch and convert papers" and the "fetch and convert contacts" in parallel and we were keeping all of them. The sync was very slow and the UI was very slow too if we had 1000+ elements.
Here we changed the process.
1. We fetch papers and contacts in parralel
2. We filter papers and contacts to keep only what we want. We need both elements to filter them because papers and contacts are linked (for example, we want to keep contacts that are referenced in papers).
3. We convert them as ciphers
I also created a new sync.ts file to separate our code from the Bitwarden sync service.

feat: Improve performance by limiting papers and contacts synced

---

apps/browser/src/cozy/components/view-more-contacts/view-more-contacts.component.html
apps/browser/src/cozy/components/view-more-contacts/view-more-contacts.component.ts
apps/browser/src/popup/app-routing.module.ts
apps/browser/src/popup/app.module.ts
apps/browser/src/popup/scss/pages.scss
apps/browser/src/vault/popup/components/vault/vault-filter.component.html
apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
apps/browser/src/vault/popup/components/vault/vault-items.component.html
apps/browser/src/vault/popup/components/vault/vault-items.component.ts

Add more contacts button in popup

---

apps/browser/src/vault/popup/components/vault/vault-filter.component.html

In a previous commit where I tried to reduce code customization (90c2473dc552db54fec57a96c316bbae6371fa6a), I removed too much and there were no border bottom in vault in types section.

fix: Add back border bottom in vault in types section

---

apps/browser/src/vault/popup/components/vault/vault-items.component.ts

When overloading load in vault-items.component.ts, I forget to pass the deleted arguments to the parent method. So the deleted filter was not working anymore.

fix: Too many items in trash

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/_locales/fr/messages.json

Last merge upstream added an option to enable or disable identity and card in inline menu. It works out of the box for Cozy contacts. We just need to update the wording.

fix: Update identity wording

---

apps/browser/src/autofill/background/overlay.background.ts
apps/browser/src/cozy/realtime/RealtimeNotifications.ts
apps/browser/src/cozy/realtime/synchronousJobQueue.spec.ts
apps/browser/src/cozy/realtime/synchronousJobQueue.ts
libs/cozy/mapping.ts

If on Cozy Contacts, I set 4 contacts as favorite in the same time, it will send 4 contact update events very quickly to the extension. The extension did not handle the events correctly so we could have race condition where we added only part of the favorite contacts to the extension.
So we add a synchronous queue that receive events and manage them sequentially.

Fix realtime contact race condition
